---
title: Indyboymom2
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: A bold typographic theme inspired by Swiss design.
baseurl: 
url: 
github_repo: jekyll
github_username: jekyll
social_link: twitter
theme_color: "#e952e9"
social_username: jekyllrb
markdown: kramdown
repository: jmkrum/swiss
